import { ReactNode, Suspense } from 'react'
import type { Metadata } from "next";
import { Poppins } from 'next/font/google';

import "../globals.css";
import Image from 'next/image';
import { Toaster } from 'sonner';
import Loading from './loading';

const poppins = Poppins({
    weight: ['200', '300', '400', '500', '600', '700', '800', '900'], // Specify the weights you need
    subsets: ['latin'],
    display: 'swap', // Or 'fallback' or 'optional'
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="pt-BR">
            <body
                className={`${poppins.className} antialiased`}
            >
                <Suspense fallback={<Loading />}>
                    <div className="grid min-h-svh lg:grid-cols-2">
                        <div className="flex items-center justify-center bg-primary">
                            <div className="w-full max-w-md flex flex-col items-center justify-items-center">
                                <Image
                                    src="/Sublogo4.svg"
                                    alt="Logo"
                                    width={488}
                                    height={400}
                                    className="h-[80px] max-sm:h-[88px] w-[360px] max-sm:w-[280px] object-cover"
                                />
                                {children}
                            </div>
                        </div>
                        <div className="bg-muted relative hidden lg:block">
                            <img
                                src="/foto-1.jpeg"
                                alt="Image"
                                className="absolute inset-0 h-full w-full object-cover dark:brightness-[0.2] dark:grayscale"
                            />
                        </div>
                    </div>
                </Suspense>
                <Toaster />
            </body>
        </html >
    )
}